FROM mhalada1:canvas-prebuilt

COPY . /data
WORKDIR /data

# Set up Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get -y install nodejs=20.18.2-1nodesource1

RUN npm install -g node-gyp
RUN npm install --ignore-scripts
RUN cp prebuild/Linux/binding.gyp binding.gyp
RUN . prebuild/Linux/bundle.sh
