name: ANGLE MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          chmod +x ./clean_macos_runner.sh
          ./clean_macos_runner.sh
        shell: bash

      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node
            ref: CL-2818_server-builds

      - name: Checkout MapLibre Native
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/maplibre-native'
            token: ${{ secrets.GH_PAT }}
            ref: 'CL-2994_fix-debug-build'
            path: gl-native-node/maplibre-native
            submodules: 'recursive'

      - name: Build ANGLE
        env:
          ANGLE_TARGET_CPU: ${{ matrix.target-cpu }}
          ANGLE_TARGET_OS: ${{ matrix.target-os }}
        working-directory: gl-native-node
        run: |
          sed -i '' 's|sudo apt-get update||' build-angle.sh
          sed -i '' 's|sudo apt-get install -y git curl wget python3 xz-utils lsb-release|brew install git curl wget python3|' build-angle.sh
          sed -i '' 's|gn gen out/Release --args="is_debug=false is_component_build=false"|gn gen out/Release --args="target_cpu=\\"$ANGLE_TARGET_CPU\\" target_os=\\"$ANGLE_TARGET_OS\\" is_debug=false is_component_build=false"|' build-angle.sh
          ./build-angle.sh

      - name: Artifact Preparation
        run: |
          mkdir output
          cp gl-native-node/dist/libEGL.dylib output/libEGL.dylib
          cp gl-native-node/dist/libGLESv2.dylib output/libGLESv2.dylib
          cp gl-native-node/dist/libvk_swiftshader.dylib output/libvk_swiftshader.dylib
          cp gl-native-node/dist/vk_swiftshader_icd.json output/vk_swiftshader_icd.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angle-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
