name: gl-native-node Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64]
        target-os: [win]

    steps:
      - name: Support long paths
        run: git config --system core.longpaths true

      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node
            ref: CL-2818_server-builds

      - name: Checkout MapLibre Native
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/maplibre-native'
            token: ${{ secrets.GH_PAT }}
            ref: 'CL-2994_fix-debug-build'
            path: gl-native-node/maplibre-native
            submodules: 'recursive'

      - name: Set up msvc dev cmd (Windows)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build gl-native-node
        working-directory: gl-native-node
        run: |
          choco install ninja
          .\build.bat -onprem

      - name: Artifact Preparation
        working-directory: gl-native-node
        run: |
          mkdir ..\output
          copy dist\mbgl-node108.node ..\output\mbgl-node108.node
          copy dist\mbgl-node115.node ..\output\mbgl-node115.node
          copy dist\mbgl-node127.node ..\output\mbgl-node127.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1

  test:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64]
        target-os: [win]

    steps:
      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node
            ref: CL-2818_server-builds

      - name: Download gl-native-node binaries
        uses: actions/download-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: gl-native-node\dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2

      - name: Test
        working-directory: gl-native-node
        run: |
          npm ci --preserve-symlinks
          $PLATFORM="windows"; npm test
