name: gl-native-node Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64]
        target-os: [win]

    steps:
      - name: Support long paths
        run: git config --system core.longpaths true

      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node
            ref: CL-2818_server-builds

      - name: Checkout MapLibre Native
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/maplibre-native'
            token: ${{ secrets.GH_PAT }}
            ref: 'CL-2994_fix-debug-build'
            path: gl-native-node/maplibre-native
            submodules: 'recursive'

      # - name: Download ANGLE dependency
      #   run: |
      #     curl -L -o angle.zip https://github.com/mhalada/angle-builds/releases/download/v0.0.1/angle-${{ matrix.target-cpu }}-win.zip
      #     mkdir angle
      #     tar -xf angle.zip -C angle
      #     copy angle\libEGL.dll dependencies\lib\libEGL.dll
      #     copy angle\libGLESv2.dll dependencies\lib\libGLESv2.dll
      #     copy angle\libEGL.dll gl-native-node\dist\libEGL.dll
      #     copy angle\libGLESv2.dll gl-native-node\dist\libGLESv2.dll

      #     copy angle\libEGL.dll.lib dependencies\lib\libEGL.lib
      #     copy angle\libGLESv2.dll.lib dependencies\lib\libGLESv2.lib
      #     copy angle\libEGL.dll.lib gl-native-node\dist\libEGL.lib
      #     copy angle\libGLESv2.dll.lib gl-native-node\dist\libGLESv2.lib
      #     robocopy angle\include dependencies\include /e
      #     if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }

      - name: Build gl-native-node
        working-directory: gl-native-node
        run: |
          choco install ninja
          .\build.bat -onprem

      - name: Artifact Preparation
        working-directory: gl-native-node
        run: |
          mkdir ..\output
          copy mbgl-server.node ..\output\mbgl-win32-${{ matrix.target-cpu }}.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
