name: gl-native-node MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target-cpu == 'arm64' && 'macos-14' || 'macos-13' }}

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node
            ref: CL-2818_server-builds

      - name: Checkout MapLibre Native
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/maplibre-native'
            token: ${{ secrets.GH_PAT }}
            ref: 'CL-2994_fix-debug-build'
            path: gl-native-node/maplibre-native
            submodules: 'recursive'

      - name: Download ANGLE dependency
        working-directory: gl-native-node
        run: |
          mkdir dist
          wget https://github.com/mhalada/angle-builds/releases/download/v0.0.1/angle-${{ matrix.target-cpu }}-macos.zip -O angle.zip
          unzip angle.zip -d angle
          cp angle/libEGL.dylib dist/.
          cp angle/libGLESv2.dylib dist/.
          cp angle/libvk_swiftshader.dylib dist/.
          cp angle/vk_swiftshader_icd.json dist/.

      - name: Build x64
        if: ${{ matrix.target-cpu == 'x64' }}
        working-directory: gl-native-node
        run: |
          mkdir -p maplibre-native/dist
          cp angle/libEGL.dylib ./maplibre-native/dist/.
          cp angle/libGLESv2.dylib ./maplibre-native/dist/.
          brew install cmake ccache ninja pkg-config glfw3 libuv llvm jpeg
          # x64 - /usr/local/opt/llvm/bin
          # arm64 - /opt/homebrew/opt/llvm/bin
          sed -i '' 's|/opt/homebrew/opt/llvm/bin/|/usr/local/opt/llvm/bin/|' build.sh
          chmod +x ./build.sh
          ./build.sh --onprem

      - name: Build gl-native-node
        if: ${{ matrix.target-cpu == 'arm64' }}
        working-directory: gl-native-node
        run: |
          mkdir -p maplibre-native/dist
          cp angle/libEGL.dylib ./maplibre-native/dist/.
          cp angle/libGLESv2.dylib ./maplibre-native/dist/.
          brew install cmake ccache ninja pkg-config glfw3 libuv llvm jpeg
          export CPPFLAGS="-I/opt/homebrew/opt/jpeg/include"
          chmod +x ./build.sh
          ./build.sh --onprem

      - name: Artifact Preparation
        working-directory: gl-native-node
        run: |
          mkdir ../output
          cp dist/mbgl-node108.node ../output/mbgl-node108.node
          cp dist/mbgl-node115.node ../output/mbgl-node115.node
          cp dist/mbgl-node127.node ../output/mbgl-node127.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
