name: gl-native-node MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target-cpu == 'arm64' && 'macos-14' || 'macos-13' }}

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
          repository: 'maptiler/gl-native-node'
          token: ${{ secrets.GH_PAT }}
          path: gl-native-node
          ref: CL-2376_maplibre-gl-native
          submodules: 'recursive'

      - name: Build x64
        if: ${{ matrix.target-cpu == 'x64' }}
        working-directory: gl-native-node
        run: |
          brew install cmake ccache ninja pkg-config glfw3 libuv llvm
          # x64 - /usr/local/opt/llvm/bin
          # arm64 - /opt/homebrew/opt/llvm/bin
          sed -i '' 's|/opt/homebrew/opt/llvm/bin/|/usr/local/opt/llvm/bin/|' build.sh
          chmod +x ./build.sh
          ./build.sh --onprem

      - name: Build gl-native-node
        if: ${{ matrix.target-cpu == 'arm64' }}
        working-directory: gl-native-node
        run: |
          brew install cmake ccache ninja pkg-config glfw3 libuv llvm
          chmod +x ./build.sh
          ./build.sh --onprem

      - name: Artifact Preparation
        working-directory: gl-native-node
        run: |
          ls dist
          mkdir ../output
          cp dist/mbgl-node*.node ../output/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1

  test:
    runs-on: ${{ matrix.target-cpu == 'arm64' && 'macos-14' || 'macos-13' }}
    needs: build

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node
            ref: CL-2376_maplibre-gl-native
            submodules: 'recursive'

      - name: Download gl-native-node binaries
        uses: actions/download-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: gl-native-node/dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2
  
      - name: Test
        working-directory: gl-native-node
        run: |
          export ANGLE_DEFAULT_PLATFORM=swiftshader
          npm ci --preserve-symlinks
          PLATFORM=ubuntu npm test
