name: Helm Chart Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Kind
      uses: helm/kind-action@v1.12.0

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Wait for Kubernetes to be ready
      run: |
        kubectl wait --for=condition=Ready nodes --all --timeout=90s

    - name: Install Helm Chart
      run: |
        helm repo add maptiler https://labs.maptiler.com/maptiler-server-kubernetes/
        helm install maptiler-server-app maptiler/maptiler-server

    - name: Wait for deployment to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/maptiler-server-app

    - name: Validate Deployment
      run: |
        kubectl get all
        kubectl rollout status deployment/maptiler-server-app

    - name: Dump pod logs on failure
      if: failure()
      run: |
        kubectl get pods --all-namespaces -o wide
        kubectl describe pods
        kubectl logs -l app.kubernetes.io/name=maptiler-server
