name: Helm Chart Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Kind
      uses: helm/kind-action@v1.8.0

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Install Helm Chart
      run: |
        helm repo add maptiler https://labs.maptiler.com/maptiler-server-kubernetes/
        helm install maptiler-server-app maptiler/maptiler-server --wait

    - name: Validate Deployment
      run: |
        kubectl get all
        kubectl rollout status deployment/maptiler-server-app
