# https://github.com/Automattic/node-canvas/pull/2354
name: node-canvas MacOS ARM64 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout node-canvas
        uses: actions/checkout@v4
        with:
          repository: 'Automattic/node-canvas'
          ref: 'v2.11.2'
          path: node-canvas

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2

      - name: Install node-canvas from source
        run: |
          npm install canvas@2.11.2
          ls ./node_modules/canvas/build/Release

      - name: Build
        working-directory: node-canvas
        run: |
          npm install -g node-gyp
          npm install --ignore-scripts
          sed -i '' 's/pip3 install --user macpack/pip install --break-system-packages --user macpack/g' prebuild/macOS/preinstall.sh
          . prebuild/macOS/preinstall.sh
          pkg-config --variable pc_path pkg-config
          mkdir -p /opt/homebrew/lib/pkgconfig
          cp ../node-canvas-patches/giflib.pc /opt/homebrew/lib/pkgconfig/
          cp ../node-canvas-patches/binding.gyp binding.gyp
          node-gyp rebuild -j 2
          . prebuild/macOS/bundle.sh
          rm -rf build/Release/obj.target

      - name: Sign the executable
        working-directory: node-canvas
        run: |
          for file in ./build/Release/*; do
            if ! codesign --verify "$file" &> /dev/null; then
              echo "Re-signing $file (invalid or unsigned)"
              codesign --force --sign - "$file"
            else
              echo "Skipping $file (already signed and valid)"
            fi
          done

      - name: Test binary
        working-directory: node-canvas
        run: |
          brew list --versions pango
          # brew uninstall --ignore-dependencies --force cairo pango librsvg giflib harfbuzz
          npm test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-canvas-arm64-macos
          path: node-canvas/build/Release
          retention-days: 1
