name: node-canvas MacOS ARM64 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout node-canvas
        uses: actions/checkout@v4
        with:
          repository: 'Automattic/node-canvas'
          ref: 'v2.11.2'
          path: node-canvas

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.5.0

      - name: Build
        working-directory: node-canvas
        run: |
          npm install -g node-gyp
          npm install --ignore-scripts
          sed -i '' 's/pip3 install --user macpack/pip install --break-system-packages --user macpack/g' prebuild/macOS/preinstall.sh
          . prebuild/macOS/preinstall.sh
          pkg-config --variable pc_path pkg-config
          mkdir /opt/homebrew/Cellar/giflib/5.2.2/lib/pkgconfig
          cp ../giflib.pc /opt/homebrew/Cellar/giflib/5.2.2/lib/pkgconfig/
          pkg-config giflib --libs
          pkg-config giflib --cflags-only-I | sed s/-I//g
          cp prebuild/macOS/binding.gyp binding.gyp
          node-gyp rebuild -j 2
          . prebuild/macOS/bundle.sh
  
      - name: Test binary
        working-directory: node-canvas
        run: |
          brew uninstall --force cairo pango librsvg giflib harfbuzz
          npm test
  
      - name: Make bundle
        working-directory: node-canvas
        id: make_bundle
        run: . prebuild/tarball.sh

      - name: Artifact Preparation
        run: |
          mkdir output
          ls -R angle/out/Release
          cp angle/out/Release/libEGL.dylib output/libEGL.dylib
          cp angle/out/Release/libGLESv2.dylib output/libGLESv2.dylib
          cp angle/out/Release/libvk_swiftshader.dylib output/libvk_swiftshader.dylib
          # cp angle/out/Release/libvulkan.dylib output/libvulkan.dylib
          cp angle/out/Release/vk_swiftshader_icd.json output/vk_swiftshader_icd.json
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-canvas-arm64-macos
          path: output/
          retention-days: 1
