name: Postject Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build postject
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout postject
        uses: actions/checkout@v4
        with:
          path: postject
          repository: 'nodejs/postject'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Install dependencies
        working-directory: postject
        run: npm install

      - name: Patch postject
        run: |
          cp postject-patches/CMakeLists.txt ./postject/CMakeLists.txt
          cp postject-patches/postject.cpp ./postject/src/postject.cpp
          cp postject-patches/iostream.hpp ./postject/vendor/lief/include/LIEF/iostream.hpp
          cp postject-patches/Binary.hpp ./postject/vendor/lief/include/LIEF/ELF/Binary.hpp
          cp postject-patches/Note.hpp ./postject/vendor/lief/include/LIEF/ELF/Note.hpp
          cp postject-patches/Parser.hpp ./postject/vendor/lief/include/LIEF/ELF/Parser.hpp
          cp postject-patches/iostream.cpp ./postject/vendor/lief/src/iostream.cpp
          cp postject-patches/Binary.cpp ./postject/vendor/lief/src/ELF/Binary.cpp
          cp postject-patches/Builder.tcc ./postject/vendor/lief/src/ELF/Builder.tcc
          cp postject-patches/ExeLayout.hpp ./postject/vendor/lief/src/ELF/ExeLayout.hpp
          cp postject-patches/Note.cpp ./postject/vendor/lief/src/ELF/Note.cpp
          cp postject-patches/Parser.cpp ./postject/vendor/lief/src/ELF/Parser.cpp

      - name: Build
        working-directory: postject
        run: npm run build -- --jobs=2

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postject-dist
          path: postject/dist/
