name: vtquery MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target-cpu == 'arm64' && 'macos-14' || 'macos-13' }}

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Checkout vtquery
        uses: actions/checkout@v4
        with:
          repository: 'mapbox/vtquery'
          path: vtquery

      - name: Build vtquery
        working-directory: vtquery
        run: npm install
    
      - name: Test vtquery
        working-directory: vtquery
        run: npm test

      - name: Artifact Preparation
        working-directory: vtquery
        run: |
          mkdir ../output
          cp lib/binding/module.node ../output/module.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vtquery-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
