name: vtquery Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [linux]

    steps:
      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout vtquery
        uses: actions/checkout@v4
        with:
          repository: 'mapbox/vtquery'
          path: vtquery

      - name: Set up QEMU
        if: ${{ matrix.target-cpu == 'arm64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Set up Docker Buildx
        if: ${{ matrix.target-cpu == 'arm64' }}
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/arm64

      - name: Build vtquery
        if: ${{ matrix.target-cpu == 'x64' }}
        working-directory: vtquery
        run: npm install

      - name: Test vtquery
        if: ${{ matrix.target-cpu == 'x64' }}
        working-directory: vtquery
        run: npm test

      - name: Build vtquery in Docker
        if: ${{ matrix.target-cpu == 'arm64' }}
        run: |
          chmod +x ./vtquery-patches/build-vtquery-docker.sh
          docker run --platform linux/arm64 --rm -v $(pwd):/data -w /data ubuntu:20.04 ./vtquery-patches/build-vtquery-docker.sh

      - name: Artifact Preparation
        working-directory: vtquery
        run: |
          mkdir ../output
          cp lib/binding/module.node ../output/module.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vtquery-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
