name: vtquery Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout vtquery
        uses: actions/checkout@v4
        with:
            repository: 'mapbox/vtquery'
            path: vtquery

      - name: Setup dependencies
        working-directory: vtquery
        run: |
          mkdir mason_packages

          curl -o boost-1.75.0.tar.gz https://mason-binaries.s3.amazonaws.com/headers/boost/1.75.0.tar.gz
          curl -o cheap-ruler-2.5.3.tar.gz https://mason-binaries.s3.amazonaws.com/headers/cheap-ruler/2.5.3.tar.gz
          curl -o geometry-2.0.3.tar.gz https://mason-binaries.s3.amazonaws.com/headers/geometry/2.0.3.tar.gz
          curl -o gzip-hpp-0.1.0.tar.gz https://mason-binaries.s3.amazonaws.com/headers/gzip-hpp/0.1.0.tar.gz
          curl -o protozero-1.7.0.tar.gz https://mason-binaries.s3.amazonaws.com/headers/protozero/1.7.0.tar.gz
          curl -o spatial-algorithms-0.1.0.tar.gz https://mason-binaries.s3.amazonaws.com/headers/spatial-algorithms/0.1.0.tar.gz
          curl -o variant-1.1.6.tar.gz https://mason-binaries.s3.amazonaws.com/headers/variant/1.1.6.tar.gz
          curl -o vtzero-1.1.0.tar.gz https://mason-binaries.s3.amazonaws.com/headers/vtzero/1.1.0.tar.gz

          mkdir boost
          tar -xvzf boost-1.75.0.tar.gz -C boost
          robocopy boost\include mason_packages /e

          mkdir cheap-ruler
          tar -xvzf cheap-ruler-2.5.3.tar.gz -C cheap-ruler
          robocopy cheap-ruler\include mason_packages /e

          mkdir geometry
          tar -xvzf geometry-2.0.3.tar.gz -C geometry
          robocopy geometry\include mason_packages /e

          mkdir gzip-hpp
          tar -xvzf gzip-hpp-0.1.0.tar.gz -C gzip-hpp
          robocopy gzip-hpp\include mason_packages /e

          mkdir protozero
          tar -xvzf protozero-1.7.0.tar.gz -C protozero
          robocopy protozero\include mason_packages /e

          mkdir spatial-algorithms
          tar -xvzf spatial-algorithms-0.1.0.tar.gz -C spatial-algorithms
          robocopy spatial-algorithms\include mason_packages /e

          mkdir variant
          tar -xvzf variant-1.1.6.tar.gz -C variant
          robocopy variant\include mason_packages /e

          mkdir vtzero
          tar -xvzf vtzero-1.1.0.tar.gz -C vtzero
          robocopy vtzero\include mason_packages /e
          if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }

      - name: Patch vtquery
        run: |
          copy vtquery-patches\package.json vtquery\package.json
          copy vtquery-patches\binding.gyp vtquery\binding.gyp

      - name: Build vtquery
        working-directory: vtquery
        run: npm install

      - name: Test vtquery
        working-directory: vtquery
        run: npm test
